// Generated by Selenium IDE
import org.junit.*;

import static org.junit.Assert.*;
        import static org.hamcrest.CoreMatchers.is;
        import org.openqa.selenium.By;
        import org.openqa.selenium.WebDriver;
        import org.openqa.selenium.chrome.ChromeDriver;
        import org.openqa.selenium.Dimension;
        import org.openqa.selenium.JavascriptExecutor;
        import java.util.*;

public class Test_1 {
    private WebDriver driver;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver.exe");
        driver = new ChromeDriver();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    // Тут будет описание тест кейса
    @Test
    public void test10() {
        driver.get("https://www.saucedemo.com/");
        driver.manage().window().setSize(new Dimension(697, 728));
        driver.findElement(By.id("user-name")).sendKeys("standard_user");
        driver.findElement(By.id("password")).sendKeys("secret_sauce");
        driver.findElement(By.id("login-button")).click();
        driver.findElement(By.cssSelector("#item_4_title_link > .inventory_item_name")).click();
        assertThat(driver.findElement(By.cssSelector(".inventory_details_desc")).getText(), is("carry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection."));
        driver.findElement(By.id("react-burger-menu-btn")).click();
    }

    @Test
    public void QautoTest() throws InterruptedException {
        driver.get("https://guest:welcome2qauto@qauto.forstudy.space/");
        driver.findElement(By.cssSelector(".btn-outline-white")).click();
        driver.findElement(By.id("signinEmail")).sendKeys("larochkarrr@gmail.com");
        driver.findElement(By.id("signinPassword")).sendKeys("6s3RQD1skYAozSx");
        driver.findElement(By.cssSelector(".btn-primary:nth-child(2)")).click();
        Thread.sleep(2000);
        assertTrue(driver.findElement(By.linkText("Profile")).isDisplayed());

    }

//Homework#28

//User creation
    @Test
    public void QautoTest2() throws InterruptedException {
        driver.get("https://guest:welcome2qauto@qauto.forstudy.space/");
        driver.findElement(By.cssSelector(".hero-descriptor_btn")).click();
        driver.findElement(By.id("signupName")).sendKeys("Lara");
        driver.findElement(By.id("signupLastName")).sendKeys("Nazarenko");
        driver.findElement(By.id("signupEmail")).sendKeys("larochkarrr@gmail.com");
        driver.findElement(By.id("signupPassword")).sendKeys("Pro100lara");
        driver.findElement(By.id("signupRepeatPassword")).sendKeys("Pro100lara");
    }

    //Name and lastName check in the profile after the registration
    @Test
    public void QautoTest4() throws InterruptedException {
        driver.get("https://guest:welcome2qauto@qauto.forstudy.space/");
        driver.findElement(By.cssSelector(".btn-outline-white")).click();
        driver.findElement(By.id("signinEmail")).sendKeys("larochkarrr@gmail.com");
        driver.findElement(By.id("signinPassword")).sendKeys("Pro100lara");
        driver.findElement(By.cssSelector(".btn-primary:nth-child(2)")).click();
        Thread.sleep(2000);
        assertTrue(driver.findElement(By.linkText("Profile")).isDisplayed());
        driver.findElement(By.linkText("Profile")).click();
        driver.findElement(By.cssSelector(".btn-primary")).click();
        assertThat(driver.findElement(By.cssSelector(".profile_name")).getText(), is("Lara Nazarenko"));
    }

    //Create a car and expenses for it
    @Test
    public void QautoTest5() throws InterruptedException {
        driver.get("https://guest:welcome2qauto@qauto.forstudy.space/");
        driver.findElement(By.cssSelector(".btn-outline-white")).click();
        driver.findElement(By.id("signinEmail")).sendKeys("larochkarrr@gmail.com");
        driver.findElement(By.id("signinPassword")).sendKeys("Pro100lara");
        driver.findElement(By.cssSelector(".btn-primary:nth-child(2)")).click();
        Thread.sleep(2000);
        driver.findElement(By.xpath("//button[contains(.,'Add car')]")).click();
        driver.findElement(By.id("addCarBrand")).sendKeys("BMW");
        driver.findElement(By.id("addCarModel")).sendKeys("X5");
        driver.findElement(By.id("addCarMileage")).sendKeys("10");
        driver.findElement(By.cssSelector(".modal-footer > .btn-primary")).click();
        driver.findElement(By.cssSelector(".car_add-expense")).click();
        driver.findElement(By.id("addExpenseMileage")).sendKeys("11");
        driver.findElement(By.id("addExpenseLiters")).sendKeys("3");
        driver.findElement(By.id("addExpenseTotalCost")).sendKeys("1000");
        driver.findElement(By.cssSelector(".modal-footer > .btn-primary")).click();
    }

    //Remove account
    @Test
    public void QautoTest6() throws InterruptedException {
        driver.get("https://guest:welcome2qauto@qauto.forstudy.space/");
        driver.findElement(By.cssSelector(".btn-outline-white")).click();
        driver.findElement(By.id("signinEmail")).sendKeys("larochkarrr@gmail.com");
        driver.findElement(By.id("signinPassword")).sendKeys("Pro100lara");
        driver.findElement(By.cssSelector(".btn-primary:nth-child(2)")).click();
        Thread.sleep(2000);
        driver.findElement(By.linkText("Settings")).click();
        driver.findElement(By.cssSelector(".btn-danger-bg")).click();
        driver.findElement(By.cssSelector(".-remove")).click();
    }
}